sp_user_group_index:
    path: /
    defaults: { _controller:SpBarUserBundle:Backend/Group:index }

sp_user_group_list:
    path: /list/
    defaults: { _controller:SpBarUserBundle:Backend/Group:list }

sp_user_group_new:
    path: /new/
    defaults: { _controller:SpBarUserBundle:Backend/Group:new }

sp_user_group_edit:
    path: /{slug}/edit/
    defaults: { _controller:SpBarUserBundle:Backend/Group:edit }

sp_user_group_permission:
    path: /{slug}/permission
    defaults: { _controller:SpBarUserBundle:Backend/Group:permission }

sp_user_group_delete:
    path: /{slug}/delete
    defaults: { _controller:SpBarUserBundle:Backend/Group:delete }