# sp_blog_post_index:
#     path: /
#     defaults: { _controller: SpBarBlogBundle:Backend/Post:index }

# sp_blog_post_list:
#     path: /list/
#     defaults: { _controller: SpBarBlogBundle:Backend/Post:list }

sp_blog_comment_new:
    path: /new/
    defaults: { _controller: SpBarBlogBundle:Backend/Comment:new }

sp_blog_comment_reply:
    path: /reply/
    defaults: { _controller: SpBarBlogBundle:Backend/Comment:reply }

sp_blog_comment_edit:
    path: /edit
    defaults: { _controller: SpBarBlogBundle:Backend/Comment:edit }

sp_blog_comment_delete:
    path: /delete
    defaults: { _controller: SpBarBlogBundle:Backend/Comment:delete }