sp_blog_config_index:
    path: /
    defaults: { _controller: SpBarBlogBundle:Backend/Config:index }

sp_blog_config_default:
    path: /default/
    defaults: { _controller: SpBarBlogBundle:Backend/Config:default }

sp_blog_config_list:
    path: /list/
    defaults: { _controller: SpBarBlogBundle:Backend/Config:list }

sp_blog_config_new:
    path: /new/
    defaults: { _controller: SpBarBlogBundle:Backend/Config:new }

sp_blog_config_edit:
    path: /{slug}/edit/
    defaults: { _controller: SpBarBlogBundle:Backend/Config:edit }

sp_blog_config_delete:
    path: /{slug}/delete/
    defaults: { _controller: SpBarBlogBundle:Backend/Config:delete }