sp_blog_front:
    resource: "@SpBarBlogBundle/Resources/config/frontend/front_all_routing.yml"
    prefix:   /

sp_blog_back:
    resource: "@SpBarBlogBundle/Resources/config/backend/back_all_routing.yml"
    prefix:   /admin/blog