sp_blog_front_home_index:
    path: /
    defaults: { _controller: SpBarBlogBundle:Frontend/Home:index }

# sp_blog_front_post_authorPost:
#     path: /sp-{user}/posts/
#     defaults: { _controller: SpBarBlogBundle:Frontend/Post:authorPost }

sp_blog_front_home_single:
    path: /{slug}/
    defaults: { _controller: SpBarBlogBundle:Frontend/Home:single }