sp_blog_front_home_index:
    path: /
    defaults: { _controller: SpBarBlogBundle:Frontend/Home:index }

sp_blog_front_home_author:
    path: /author/{author}/
    defaults: { _controller: SpBarBlogBundle:Frontend/Home:author }

sp_blog_front_home_single:
    path: /category/{cat_slug}/{slug}/
    defaults: { _controller: SpBarBlogBundle:Frontend/Home:single }

sp_blog_front_home_category:
    path: /category/{cat_slug}/
    defaults: { _controller: SpBarBlogBundle:Frontend/Home:category }

sp_blog_front_home_page:
    path: /{page_slug}/
    defaults: { _controller: SpBarBlogBundle:Frontend/Home:page }

